[profile.default]
src = 'contracts'
out = 'out'
libs = [
    'lib'
]
remappings = [
    "forge-std/=lib/forge-std/src/"
]
ffi=true
verbosity=5

# See more config options https://github.com/foundry-rs/foundry/tree/master/config