[profile.default]
src = 'contracts'
out = 'out'
remappings = [
    "forge-std/=lib"
]
libs = [
    'lib'
]

ffi=true
verbosity=5

# See more config options https://github.com/foundry-rs/foundry/tree/master/config